name       : deepin-calculator
version    : 1.0.2
release    : 7
source     :
    - git|https://cr.deepin.io/deepin-calculator.git : 1.0.2
license    : GPL-3.0
component  : desktop.deepin
summary    : An easy to use calculator for ordinary users.
description: |
    Deepin calculator is an easy to use calculator for ordinary users.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(Qt5Svg)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5integration
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
