name       : deepin-dock
version    : 4.5.0
release    : 1
source     :
    - https://github.com/linuxdeepin/dde-dock/archive/4.5.0.tar.gz : ef3faae63bef536d57c618daf9aa515a6b478308d3f96d2cb1af3e3edfc729d8
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin Dock is the dock of Deepin Desktop Environment.
description: |
    Deepin Dock is the dock of Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-image)
    - pkgconfig(xtst)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
