name       : deepin-dock
version    : 4.6.3.3
release    : 13
source     :
    - git|https://cr.deepin.io/dde/dde-dock.git : 8d0bdbf6aaa59e92f742ad056c8210505ff7cf13
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin Dock is the dock of Deepin Desktop Environment.
description: |
    Deepin Dock is the dock of Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-image)
    - pkgconfig(xtst)
    - qt5-tools-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-CMakeLists-Remove-arch-check.patch
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
