name       : deepin-gtk-theme
version    : 17.10.6
release    : 5
source     :
    - https://github.com/linuxdeepin/deepin-gtk-theme/archive/17.10.6.tar.gz : 4aabd151a789c48587fa3e01bc14cf8df72f96200cce9f7d489f1893734d3951
license    : GPL-3.0
component  : desktop.theme
summary    : Deepin GTK Theme.
description: |
    Deepin GTK Theme.
build      : |
    %make
install    : |
    %make_install
