name       : deepin-gtk-theme
version    : 17.10.7
release    : 11
source     :
    - git|https://github.com/linuxdeepin/deepin-gtk-theme.git : 17.10.7
license    : GPL-3.0
component  : desktop.theme
summary    : Deepin GTK Theme.
description: |
    Deepin GTK Theme.
build      : |
    %make
install    : |
    %make_install
