name       : deepin-gtk-theme
version    : 17.10.10
release    : 17
source     :
    - git|https://github.com/linuxdeepin/deepin-gtk-theme.git : 17.10.10
license    : LGPL-3.0-or-later
component  : desktop.theme
summary    : Deepin GTK Theme.
description: |
    Deepin GTK Theme.
build      : |
    %make
install    : |
    %make_install
