name       : deepin-gtk-theme
version    : 17.10.8
release    : 12
source     :
    - git|https://github.com/linuxdeepin/deepin-gtk-theme.git : 17.10.8
license    : GPL-3.0
component  : desktop.theme
summary    : Deepin GTK Theme.
description: |
    Deepin GTK Theme.
build      : |
    %make
install    : |
    %make_install
