name       : python-jieba
version    : 0.39
release    : 1
source     :
    - https://github.com/fxsjy/jieba/archive/v0.39.tar.gz : 20a8759f90be798c1f78238972b2908e289cac024b59c8a6e541499a5247462b
license    : MIT
component  : programming.python
summary    : Chinese Words Segementation Utilities
description: |
    Chinese Words Segementation Utilities
build      : |
    %python_setup
install    : |
    %python_install
