name       : deepin-api
version    : 3.1.19
release    : 2
source     :
    - https://github.com/linuxdeepin/dde-api/archive/3.1.19.tar.gz : 53095f900d9834382d4a3eb98c1712fe2ca08e7fb975ea377bb4f43487e2ff7a
extract    : no
networking : yes
license    : GPL-3.0
component  : programming.library
summary    : Go-lang bindings for deepin-daemon
description: |
    Go-lang bindings for deepin-daemon
rundeps    :
    - blur-effect
    - deepin-desktop-base
    - rfkill
    - xcur2png
builddeps  :
    - deepin-dbus-factory
    - deepin-gettext-tools
    - deepin-go-lib
    - deepin-gir-generator
    - git
    - golang
    - pkgconfig(alsa)
    - pkgconfig(gdk-3.0)
    - pkgconfig(libpulse-simple)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(poppler-glib)
    - pkgconfig(libcanberra)
setup      : |
    mkdir {bin,pkg,src}
    mkdir -p src/github.com/linuxdeepin/
    tar xf $sources/$version.tar.gz -C src/github.com/linuxdeepin/
    mv src/github.com/linuxdeepin/dde-api-$version src/github.com/linuxdeepin/dde-api
    pushd src/github.com/linuxdeepin/dde-api
    popd
    mkdir -p src/pkg.deepin.io
build      : |
    export GOPATH=$workdir/:/usr/share/gocode
    go get gopkg.in/alecthomas/kingpin.v2
    go get github.com/nfnt/resize
    go get github.com/cryptix/wav
    pushd src/github.com/linuxdeepin/dde-api
    make build-dep
    %make
    popd
install    : |
    export GOPATH=$workdir/:/usr/share/gocode
    pushd src/github.com/linuxdeepin/dde-api
    %make_install libdir=/lib64
    popd
