name       : deepin-api
version    : 3.1.22
release    : 4
source     :
    - https://github.com/linuxdeepin/dde-api/archive/3.1.22.tar.gz : c7355da4238957f95322c06e4104c52f2a18c908b17d7c22625b98bb6127859f
extract    : no
networking : yes
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Go-lang bindings for deepin-daemon
description: |
    Go-lang bindings for deepin-daemon
rundeps    :
    - deepin-desktop-base
    - xcur2png
builddeps  :
    - deepin-dbus-factory
    - deepin-gettext-tools
    - deepin-gir-generator
    - deepin-go-lib
    - git
    - golang
    - pkgconfig(alsa)
    - pkgconfig(gdk-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse-simple)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(poppler-glib)
setup      : |
    mkdir {bin,pkg,src}
    mkdir -p src/github.com/linuxdeepin/
    tar xf $sources/$version.tar.gz -C src/github.com/linuxdeepin/
    mv src/github.com/linuxdeepin/dde-api-$version src/github.com/linuxdeepin/dde-api
    pushd src/github.com/linuxdeepin/dde-api
    popd
    mkdir -p src/pkg.deepin.io
build      : |
    export GOPATH=$workdir/:/usr/share/gocode
    go get gopkg.in/alecthomas/kingpin.v2
    go get github.com/nfnt/resize
    go get github.com/cryptix/wav
    pushd src/github.com/linuxdeepin/dde-api
    make build-dep
    %make
    popd
install    : |
    export GOPATH=$workdir/:/usr/share/gocode
    pushd src/github.com/linuxdeepin/dde-api
    %make_install libdir=/lib64
    popd
