name       : deepin-go-lib
version    : 1.2.3
release    : 2
source     :
    - https://github.com/linuxdeepin/go-lib/archive/1.2.3.tar.gz : a056396c038d1f6d8687fe0b5196b16ae7503bea480ae867b9200bffb9e193e3
license    : GPL-3.0
component  : programming.library
summary    : A library containing many useful go routines for things such as glib, gettext, archive, graphic,etc.
description: |
    A library containing many useful go routines for things such as glib, gettext, archive, graphic,etc.
install    : |
    mkdir -p %installroot%/usr/share/gocode/src/pkg.deepin.io/lib
    cp -a ./ %installroot%/usr/share/gocode/src/pkg.deepin.io/lib

