name       : deepin-go-lib
version    : 1.2.6
release    : 5
source     :
    - https://github.com/linuxdeepin/go-lib/archive/1.2.6.tar.gz : 57f1f70e800915cdcc0821146fb4b71289b511b4a54b504238daafa8444f4781
license    : GPL-3.0
component  : programming.library
summary    : A library containing many useful go routines for things such as glib,
    gettext, archive, graphic, etc.
description: |
    A library containing many useful go routines for things such as glib, gettext, archive, graphic, etc.
install    : |
    mkdir -p %installroot%/usr/share/gocode/src/pkg.deepin.io/lib
    cp -a ./ %installroot%/usr/share/gocode/src/pkg.deepin.io/lib

