name       : deepin-go-lib
version    : 1.2.1
release    : 1
source     :
    - https://github.com/linuxdeepin/go-lib/archive/1.2.1.tar.gz : 2deadf02d04cfbc1ae09c61e145f8bd1339902febcd1f57a771717327cb546de
license    : GPL-3.0
component  : programming.library
summary    : A library containing many useful go routines for things such as glib, gettext, archive, graphic,etc.
description: |
    A library containing many useful go routines for things such as glib, gettext, archive, graphic,etc.
install    : |
    mkdir -p %installroot%/usr/share/gocode/src/pkg.deepin.io/lib
    cp -a ./ %installroot%/usr/share/gocode/src/pkg.deepin.io/lib

