name       : deepin-go-lib
version    : 1.2.4
release    : 3
source     :
    - https://github.com/linuxdeepin/go-lib/archive/1.2.4.tar.gz : 58bae9c3c79fd698258b708a0bdc76326816670299f056b90d5269adf5006bae
license    : GPL-3.0
component  : programming.library
summary    : A library containing many useful go routines for things such as glib, gettext, archive, graphic, etc.
description: |
    A library containing many useful go routines for things such as glib, gettext, archive, graphic, etc.
install    : |
    mkdir -p %installroot%/usr/share/gocode/src/pkg.deepin.io/lib
    cp -a ./ %installroot%/usr/share/gocode/src/pkg.deepin.io/lib

