name       : deepin-go-lib
version    : 1.2.16
release    : 20
source     :
    - git|https://github.com/linuxdeepin/go-lib.git : 1.2.16
license    : GPL-3.0
component  : programming.library
summary    : A library containing many useful go routines for things such as glib,
    gettext, archive, graphic, etc.
description: |
    A library containing many useful go routines for things such as glib, gettext, archive, graphic, etc.
install    : |
    mkdir -p %installroot%/usr/share/gocode/src/pkg.deepin.io/lib
    cp -a ./ %installroot%/usr/share/gocode/src/pkg.deepin.io/lib
    rm -r %installroot%/usr/share/gocode/src/pkg.deepin.io/lib/.git
