name       : deepin-desktop-base
version    : 2018.03.19
release    : 7
source     :
    - git|https://cr.deepin.io/deepin-desktop-base.git : 2018.03.19
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Base component for Deepin.
description: |
    Base component for Deepin.
setup      : |
    %patch -p1 < $pkgfiles/libdir.patch
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir%
    rm "${installdir}/etc/lsb-release"
    rm -r "${installdir}/etc/systemd"
    ln -s ..%libdir%/deepin/desktop-version "${installdir}/etc/deepin-version"
    rm -r "${installdir}/usr/share/python-apt"
