name       : deepin-desktop-base
version    : 2017.11.2
release    : 4
source     :
    - https://github.com/linuxdeepin/deepin-desktop-base/archive/2017.11.2.tar.gz : 4c58e7c69a00ef06ceba610912278732938c1c8bc46e7f5d02aa9d683e44b177
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Base component for Deepin.
description: |
    Base component for Deepin.
setup      : |
    %patch -p1 < $pkgfiles/libdir.patch
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir%
    rm "${installdir}/etc/lsb-release"
    rm -r "${installdir}/etc/systemd"
    ln -s ..%libdir%/deepin/desktop-version "${installdir}/etc/deepin-version"
    rm -r "${installdir}/usr/share/python-apt"
