name       : deepin-qt5integration
version    : 0.2.8.1
release    : 1
source     :
    - https://github.com/linuxdeepin/qt5integration/archive/0.2.8.1.tar.gz : a07c9ea0bd9332cc0f470398dae6b4d66378c6a494c5f487201abba2f674c2cd
license    : GPL-3.0
component  : programming.library
summary    : Qt platform theme integration plugins for DDE
description: |
    The Qt platform theme integration plugins for Deepin Desktop Environment. It includes multiple Qt5 plugins to make make DDE more Qt5 Apps friendly.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(mtdev)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5Xdg)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5dxcb-plugin
    - qtstyleplugins
setup      : |
    %patch -p1 < $pkgfiles/version.patch
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
