name       : deepin-qt5integration
version    : 0.2.10
release    : 11
source     :
    - git|https://cr.deepin.io/qt5integration.git : 0.2.10
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Qt platform theme integration plugins for DDE
description: |
    The Qt platform theme integration plugins for Deepin Desktop Environment. It includes multiple Qt5 plugins to make make DDE more Qt5 Apps friendly.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(mtdev)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5Xdg)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5dxcb-plugin
setup      : |
    %patch -p1 < $pkgfiles/version.patch
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
