name       : deepin-qt5integration
version    : 0.2.8.3
release    : 2
source     :
    - https://github.com/linuxdeepin/qt5integration/archive/0.2.8.3.tar.gz : ceb72f35b1b223f209c34c39d1c82cc7de1eb6e5c503724bf58c6120a1a8f3b8
license    : GPL-3.0
component  : programming.library
summary    : Qt platform theme integration plugins for DDE
description: |
    The Qt platform theme integration plugins for Deepin Desktop Environment. It includes multiple Qt5 plugins to make make DDE more Qt5 Apps friendly.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(mtdev)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5Xdg)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5dxcb-plugin
    - qtstyleplugins
setup      : |
    %patch -p1 < $pkgfiles/version.patch
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
