name       : deepin-manual
version    : 2.0.3
release    : 3
source     :
    - https://github.com/linuxdeepin/deepin-manual/archive/2.0.3.tar.gz : 20d8202fcc763f2659b72945fae376abae5b2e0cfc0e89ebb304a1f1a229595f
license    : GPL-3.0
component  : desktop
summary    : Deepin User Manual
description: |
    Deepin User Manual
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
#    - pkgconfig(libqcef)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebChannel)
    - qt5-tools-devel
#    - nodejs
#    - sassc
#    - yarn
#rundeps    :
#    - deepin-qml-widgets
#    - python-dae
#    - python-gobject
#    - python-jieba
#    - python-qtpy
build      : |
    mkdir build
    pushd build
    %cmake ..
    popd
install    : |
    %make_install
