name       : deepin-sound-theme
version    : 15.10.2
release    : 2
source     :
    - https://github.com/linuxdeepin/deepin-sound-theme/archive/15.10.2.tar.gz : 64c774f1741bffbdae63fde68b15771ab7c569db6a1c3a6c058b525f0eef8db5
license    : GPL-3.0
component  : desktop.theme
summary    : The freedesktop sound theme for Deepin.
description: |
    The freedesktop sound theme for Deepin.
install    : |
    %make_install
