name       : deepin-editor
version    : 0.0.4
release    : 1
source     :
    - git|https://cr.deepin.io/deepin-editor.git : 0.0.4
license    : GPL-3.0
component  : desktop.deepin
summary    : Deepin Editor.
description: |
    Deepin Editor: simple editor for deepin.
builddeps  :
    - kcodecs-devel
    - pkgconfig(dtkwidget)
    - pkgconfig(dtkwm)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcb-util)
    - pkgconfig(xext)
    - pkgconfig(xtst)
    - qt5-tools-devel
    - syntax-highlighting-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
