name       : deepin-session-ui
version    : 4.3.3
release    : 9
source     :
    - https://github.com/linuxdeepin/dde-session-ui/archive/4.3.3.tar.gz : 9f4f31c8dce1ce439114f05a3ff3605ec69560573fe99c885353041dd6286f35
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin desktop-environment - Session UI module
description: |
    Deepin desktop-environment - Session UI module
builddeps  :
    - deepin-gettext-tools
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(gsettings-qt)
    - pkgconfig(liblightdm-qt5-3)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - pkgconfig(xtst)
    - qt5-tools-devel
rundeps    :
    - deepin-daemon
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
