name       : deepin-session-ui
version    : 4.3.1
release    : 4
source     :
    - https://github.com/linuxdeepin/dde-session-ui/archive/4.3.1.tar.gz : 06db9b0795813fa1427ea7bbb07ab68f75b30b373eff87343263eeb37cef8465
license    : GPL-3.0
component  : desktop
summary    : Deepin desktop-environment - Session UI module
description: |
    Deepin desktop-environment - Session UI module
builddeps  :
    - deepin-gettext-tools
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gsettings-qt)
    - pkgconfig(gl)
    - pkgconfig(liblightdm-qt5-3)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - pkgconfig(xtst)
    - qt5-tools-devel
rundeps    :
    - deepin-control-center
    - deepin-daemon
    - startdde
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
