name       : deepin-session-ui
version    : 4.3.5
release    : 10
source     :
    - https://github.com/linuxdeepin/dde-session-ui/archive/4.3.5.tar.gz : 9da25b2af28ff69a4f936f1237fd92ed36d63d143e9eadc23d7899a04b178663
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin desktop-environment - Session UI module
description: |
    Deepin desktop-environment - Session UI module
builddeps  :
    - deepin-gettext-tools
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(gsettings-qt)
    - pkgconfig(liblightdm-qt5-3)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - pkgconfig(xtst)
    - qt5-tools-devel
rundeps    :
    - deepin-daemon
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
