name       : deepin-session-ui
version    : 4.3.2
release    : 7
source     :
    - https://github.com/linuxdeepin/dde-session-ui/archive/4.3.2.tar.gz : d5f482fce32f2b0a139c441244b063da570cb0ce642ea733088b18bde549ec5a
license    : GPL-3.0
component  : desktop
summary    : Deepin desktop-environment - Session UI module
description: |
    Deepin desktop-environment - Session UI module
builddeps  :
    - deepin-gettext-tools
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gsettings-qt)
    - pkgconfig(gl)
    - pkgconfig(liblightdm-qt5-3)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - pkgconfig(xtst)
    - qt5-tools-devel
rundeps    :
    - deepin-daemon
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
