name       : liblightdm-qt5
version    : 1.24.0
release    : 4
source     :
    - https://launchpad.net/lightdm/1.24/1.24.0/+download/lightdm-1.24.0.tar.xz : cd509b74382bcf382c6e3e4b54ac30ba804022fec968d6993d134552ea1a43a2
license    : LGPL-3.0
component  : desktop.lightdm
summary    : LightDM Qt client library.
description: |
    LightDM Qt client library.
builddeps  :
    - itstool
    - libgcrypt-devel
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(libxklavier)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(yelp-xsl)
    - yelp-devel
    - yelp-tools
rundep     :
    - lightdm
    - qt5-base
setup      : |
    export MOC4='moc-qt4'
    export MOC5='moc'
    sed -i -e 's:getgroups:lightdm_&:' tests/src/libsystem.c
    %apply_patches
    %reconfigure --enable-introspection \
                 --enable-liblightdm-gobject \
                 --disable-static \
                 --disable-tests \
                 --libexecdir=%libdir%/lightdm \
                 --with-greeter-session=lightdm-gtk-greeter \
                 --enable-liblightdm-qt5
build      : |
    export MOC4='moc-qt4'
    export MOC5='moc'
    %make -j1
install    : |
    export MOC4='moc-qt4'
    export MOC5='moc'
    make DESTDIR="%installroot%" -C liblightdm-qt install
