name       : liblightdm-qt5
version    : 1.26.0
release    : 26
source     :
    - https://github.com/CanonicalLtd/lightdm/releases/download/1.26.0/lightdm-1.26.0.tar.xz : c95e14e9131b5f95ecba42faaab2cfa917371193caa54fa1b4322ad7a89334f0
homepage   : https://github.com/CanonicalLtd/lightdm
license    :
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : desktop.lightdm
conflicts  :
    - gdm
    - sddm
summary    : LightDM Qt client library.
description: |
    LightDM Qt client library.
builddeps  :
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(libxklavier)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(yelp-xsl)
    - itstool
    - libgcrypt-devel
    - vala
    - yelp-devel
    - yelp-tools
rundeps    :
    - linux-driver-management-lightdm-integration
    - setxkbmap
    - xauth
    - xhost
    - xkbcomp
    - xkeyboard-config
setup      : |
    export MOC4='moc-qt4'
    export MOC5='moc'
    sed -i -e 's:getgroups:lightdm_&:' tests/src/libsystem.c
    %apply_patches
    %reconfigure --enable-introspection \
                 --enable-liblightdm-gobject \
                 --disable-static \
                 --disable-tests \
                 --libexecdir=%libdir%/lightdm \
                 --with-greeter-session=lightdm-gtk-greeter \
                 --enable-liblightdm-qt5
build      : |
    export MOC4='moc-qt4'
    export MOC5='moc'
    %make -j1
install    : |
    export MOC4='moc-qt4'
    export MOC5='moc'
    make DESTDIR="%installroot%" -C liblightdm-qt install
