name       : deepin-music
version    : 3.1.8.1
release    : 1
source     :
    - https://github.com/linuxdeepin/deepin-music/archive/3.1.8.1.tar.gz : 7863feaba3af0dae846a02b7938d8c1e70a40a371c17dc337817be11e29c063d
license    : GPL-3.0
component  : desktop.deepin
summary    : Music player for the Deepin DE
description: |
    Deepin Music is an application developed by Deepin Technology Team which focused on local music playing. It brings all brand new UI design, extreme playing experience, and it has local music scanning and lyric sync functions, etc.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(icu-uc)
    - pkgconfig(libavcodec)
    - pkgconfig(libavformat)
    - pkgconfig(libavutil)
    - pkgconfig(libcue)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(taglib_c)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
