name       : deepin-music
version    : 3.1.8.3
release    : 8
source     :
    - git|https://cr.deepin.io/deepin-music.git : 3.1.8.3
license    : GPL-3.0
component  : desktop.deepin
summary    : Music player for the Deepin DE
description: |
    Deepin Music is an application developed by Deepin Technology Team which focused on local music playing. It brings all brand new UI design, extreme playing experience, and it has local music scanning and lyric sync functions, etc.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(icu-uc)
    - pkgconfig(libavcodec)
    - pkgconfig(libavformat)
    - pkgconfig(libavutil)
    - pkgconfig(libcue)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(taglib_c)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5integration
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
