name       : deepin-launcher
version    : 4.3.2.2
release    : 8
source     :
    - git|https://cr.deepin.io/dde/dde-launcher.git : 4.3.2.2
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Launcher for the Deepin Desktop Environment.
description: |
    Launcher for the Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
