name       : deepin-launcher
version    : 4.2.5
release    : 1
source     :
    - https://github.com/linuxdeepin/dde-launcher/archive/4.2.5.tar.gz : b56a7ca7c57b326355a05ce016e26ff9537d6fb9a34183248eb2da3054e363f4
license    : GPL-2.0 # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
#builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
