name       : deepin-launcher
version    : 4.3.0
release    : 2
source     :
    - https://github.com/linuxdeepin/dde-launcher/archive/4.3.0.tar.gz : a9a465af4e2db9526670ae16b974dc2bfe630140b840a46bbc47fca0c78b1c07
license    : GPL-3.0
component  : desktop
summary    : Launcher for the Deepin Desktop Environment.
description: |
    Launcher for the Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - pkgconfig(xcb-ewmh)
    - qt5-tools-devel
rundeps    :
    - deepin-daemon
    - deepin-menu
    - startdde
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
