name       : libmongoc
version    : 1.9.5
release    : 11
source     :
    - https://github.com/mongodb/mongo-c-driver/archive/1.9.5.tar.gz : 5bd897c0e6a8788f30fc02f4e38d0a319f8bb8536ae291c5d76ec2a537a8b30b
license    : Apache-2.0
component  : programming.library
summary    : A high-performance MongoDB driver for C
description: |
    mongo-c-driver is a client library written in C for MongoDB.
builddeps  :
    - pkgconfig(libbson-1.0)
    - pkgconfig(libsasl2)
    - snappy-devel
setup      : |
    %patch -p1 < $pkgfiles/autogen.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
    libtool --finish $installdir/%libdir%
