name       : libmongoc
version    : 1.9.4
release    : 9
source     :
    - https://github.com/mongodb/mongo-c-driver/archive/1.9.4.tar.gz : 993183401d73498649a0016c024c002e2a069d39428d9d77a6469b0bc5635315
license    : Apache-2.0
component  : programming.library
summary    : A high-performance MongoDB driver for C
description: |
    mongo-c-driver is a client library written in C for MongoDB.
builddeps  :
    - pkgconfig(libbson-1.0)
    - pkgconfig(libsasl2)
    - snappy-devel
setup      : |
    %patch -p1 < $pkgfiles/autogen.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
    libtool --finish $installdir/%libdir%
