name       : udisks2-qt5
version    : 0.0.1
release    : 1
source     :
    - git|https://github.com/linuxdeepin/udisks2-qt5.git : 0.0.1
license    : GPL-2.0-or-later
component  : desktop.deepin
summary    : UDisks2 Library with Qt5
description: |
    UDisks2 Library with Qt5
builddeps  :
    - qt5-tools-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
