name       : deepin-control-center
version    : 4.3.4
release    : 2
source     :
    - https://github.com/linuxdeepin/dde-control-center/archive/4.3.4.tar.gz : feac32526792d5eef4439671864f2bdc1776cb425cdb3c56c6ced2e9cdd62bb3
license    : GPL-3.0
component  : desktop
summary    : Control panel of the Deepin Desktop Environment.
description: |
    Control panel of the Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(geoip)
    - pkgconfig(gl)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - qt5-tools-devel
rundeps    :
    - deepin-account-faces
    - deepin-artwork-themes
    - deepin-dock
    - deepin-qt5integration
    - startdde
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
