name       : deepin-control-center
version    : 4.4.4.1
release    : 13
source     :
    - git|https://cr.deepin.io/dde/dde-control-center : 4.4.4.1
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Control panel of the Deepin Desktop Environment.
description: |
    Control panel of the Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(geoip)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - pkgconfig(xext)
    - qt5-tools-devel
rundeps    :
    - deepin-account-faces
    - deepin-api
    - deepin-daemon
    - deepin-qt-dbus-factory
    - deepin-qt5integration
    - proxychains-ng
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
