name       : deepin-control-center
version    : 4.6.3
release    : 26
source     :
    - git|https://github.com/linuxdeepin/dde-control-center.git : 4.6.3
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Control panel of the Deepin Desktop Environment.
description: |
    Control panel of the Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dde-network-utils)
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(geoip)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - pkgconfig(xext)
    - qt5-tools-devel
rundeps    :
    - deepin-account-faces
    - deepin-api
    - deepin-daemon
    - deepin-qt-dbus-factory
    - deepin-qt5integration
    - proxychains-ng
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir% DISABLE_SYS_UPDATE=YES
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
