name       : deepin-control-center
version    : 4.4.1
release    : 8
source     :
    - https://github.com/linuxdeepin/dde-control-center/archive/4.4.1.tar.gz : 7bc98c52b1c1b49210c1a1a1d011d87cd6133732f432c4c84e7b780607199853
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Control panel of the Deepin Desktop Environment.
description: |
    Control panel of the Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(geoip)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - pkgconfig(xext)
    - qt5-tools-devel
rundeps    :
    - deepin-account-faces
    - deepin-api
    - deepin-daemon
    - deepin-qt-dbus-factory
    - deepin-qt5integration
    - proxychains-ng
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
