name       : deepin-control-center
version    : 4.3.7
release    : 3
source     :
    - https://github.com/linuxdeepin/dde-control-center/archive/4.3.7.tar.gz : e1d5b706f47443d9474165f4bddeec468faffc96c35d687286429146c1934542
license    : GPL-3.0
component  : desktop
summary    : Control panel of the Deepin Desktop Environment.
description: |
    Control panel of the Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(geoip)
    - pkgconfig(gl)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - qt5-tools-devel
rundeps    :
    - deepin-account-faces
    - deepin-api
    - deepin-artwork-themes
    - deepin-daemon
    - deepin-dock
    - deepin-qt5integration
    - startdde
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
