name       : deepin-qml-widgets
version    : 2.3.6
release    : 1
source     :
    - https://github.com/linuxdeepin/deepin-qml-widgets/archive/2.3.6.tar.gz : ed6b46bc02d9bf5471e37f559664c107672c97430912a159fad4df2507952b38
license    : GPL-3.0
component  : desktop.deepin-core
summary    : Deepin QML widgets
description: |
    Deepin QML widgets
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcomposite)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
