name       : deepin-menu
version    : 3.3.2
release    : 8
source     :
    - https://github.com/linuxdeepin/deepin-menu/archive/3.3.2.tar.gz : e5787345b350548d2b9ac6002245d35091307db121954fa7da03a6da736e6021
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin Menu is the unified menu service for Deepin Desktop Environment.
description: |
    Deepin Menu is the unified menu service for Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
    install -dm 755 "${installdir}/usr/share/dbus-1/services/"
    install -dm 755 "${installdir}/etc/xdg/autostart/"
    install -m 644 data/*.service "${installdir}/usr/share/dbus-1/services/"
    install -m 644 *.desktop "${installdir}/etc/xdg/autostart/"
