name       : deepin-menu
version    : 3.2.0
release    : 3
source     :
    - git|https://github.com/linuxdeepin/deepin-menu.git : d63251a7b96ef992d3e5a95adab9c82bc651946a
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin Menu is the unified menu service for Deepin Desktop Environment.
description: |
    Deepin Menu is the unified menu service for Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
    install -dm 755 "${installdir}/usr/share/dbus-1/services/"
    install -dm 755 "${installdir}/etc/xdg/autostart/"
    install -m 644 data/*.service "${installdir}/usr/share/dbus-1/services/"
    install -m 644 *.desktop "${installdir}/etc/xdg/autostart/"
