name       : deepin-menu
version    : 3.3.1
release    : 6
source     :
    - https://github.com/linuxdeepin/deepin-menu/archive/3.3.1.tar.gz : 4b9013563d5196ea8017edf1a5b0939422a78f2e992c0aa838ce3f9728534f54
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin Menu is the unified menu service for Deepin Desktop Environment.
description: |
    Deepin Menu is the unified menu service for Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
    install -dm 755 "${installdir}/usr/share/dbus-1/services/"
    install -dm 755 "${installdir}/etc/xdg/autostart/"
    install -m 644 data/*.service "${installdir}/usr/share/dbus-1/services/"
    install -m 644 *.desktop "${installdir}/etc/xdg/autostart/"
