name       : deepin-mutter
version    : 3.20.29
release    : 4
source     :
    - https://github.com/linuxdeepin/deepin-mutter/archive/3.20.29.tar.gz : 7cf2ce008bb0a4a15a2f85f2023b34bd5d126047b6ba46b4ca3e56b8a3e93e93
license    : GPL-3.0
component  : desktop
summary    : Base window manager for Deepin, fork of Gnome Mutter
description: |
    Base window manager for Deepin, fork of Gnome Mutter
ccache     : no
builddeps  :
    - deepin-clutter-devel
    - gnome-common
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xtst)
    - zenity
rundeps    :
    - dconf
    - deepin-desktop-schemas
    - zenity
setup      : |
    %autogen --sysconfdir=/etc \
    --libexecdir=%libdir%/deepin-mutter \
    --localstatedir=/var \
    --enable-gtk-doc \
    --enable-wayland \
    --enable-native-backend \
    --disable-static \
    --disable-schemas-compile \
    --enable-compile-warnings=minimum
build      : |
    %make
install    : |
    %make_install
