name       : jxrlib
version    : 0.2.0
release    : 1
source     :
    - https://github.com/glencoesoftware/jxrlib/archive/v0.2.0.tar.gz : 5bc79bd563b22149bd9bdb9f4b42c1ced10c94f90c782cac9712f270cbbf10ef
license    : BSD-2-Clause
component  : multimedia.graphics
summary    : Open source implementation of jpegxr
description: |
    An open source implementation of the jpegxr image format standard.
builddeps  :
    - openjdk-8-devel
    - swig
setup      : |
    %patch -p1 < $pkgfiles/usecmake.patch
    %cmake
build      : |
    %make SHARED=1 PREFIX=/usr
install    : |
    %make_install DIR_INSTALL=$installdir
