name       : libqtxdg
version    : 3.1.0
release    : 5
source     :
    - https://github.com/lxde/libqtxdg/releases/download/3.1.0/libqtxdg-3.1.0.tar.xz : 0ee1a4684b782e34950c55dc06df1b4ef2dc3d9b3562a512de004191c18a2e08
license    : LGPL-2.1
component  : programming.library
summary    : A Qt 5 implementation of freedesktop.org XDG specifications.
description: |
    A Qt 5 implementation of freedesktop.org XDG specifications.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Svg)
    - qt5-base-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
