name       : dtkwidget
version    : 2.0.7.3
release    : 15
source     :
    - git|https://cr.deepin.io/dtkwidget.git : 2.0.7.3
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Base development tool of all C++/Qt Developer work on Deepin.
description: |
    Deepin Tool Kit (Dtk) is the base development tool of all C++/Qt Developer work on Deepin.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkcore)
    - pkgconfig(gsettings-qt)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5MultimediaWidgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-util)
    - pkgconfig(xext)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
