name       : dtkwidget
version    : 2.0.6.1
release    : 5
source     :
    - https://github.com/linuxdeepin/dtkwidget/archive/2.0.6.1.tar.gz : e34909147ae6ee24ff26ac608b778f38b41562893dc028144da71eae7cc968ec
license    : GPL-3.0
component  : programming.devel
summary    : Deepint Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
description: |
    Deepint Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
builddeps  :
    - qt5-tools-devel
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkcore)
    - pkgconfig(gsettings-qt)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(Qt5MultimediaWidgets)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-util)
    - pkgconfig(xext)
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
