name       : dtkwidget
version    : 2.0.7.2
release    : 11
source     :
    - https://github.com/linuxdeepin/dtkwidget/archive/2.0.7.2.tar.gz : cd7e6e6cb55cfc435375300420e4814c9b4ac1e4d120d190a4c73d8d7068d48a
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Base devlopment tool of all C++/Qt Developer work on Deepin.
description: |
    Deepin Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkcore)
    - pkgconfig(gsettings-qt)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(Qt5MultimediaWidgets)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-util)
    - pkgconfig(xext)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
