name       : treefrog-framework
version    : 1.20.0
release    : 2
source     :
    - https://github.com/treefrogframework/treefrog-framework/archive/v1.20.0.tar.gz : 72d22e3051cea9c42ad163c9f2a706d0b47640648c594ec7c4beebb0899ee57b
license    : BSD
component  : programming.library
summary    : High-speed C++ MVC Framework for Web Application
description: |
    TreeFrog Framework is a high-speed and full-stack web application framework based on C++ and Qt, which supports HTTP and WebSocket protocol. Web applications can run faster than that of lightweight programming language. In application development, it provides an O/R mapping system and template system on an MVC architecture, aims to achieve high productivity through the policy of convention over configuration.
builddeps  :
    - qt5-tools-devel
    - qt5-declarative-devel
    - pkgconfig(Qt5Core)
    - pkgconfig(libmongoc-1.0)
setup      : |
    %patch -p1 < $pkgfiles/3rdparty.patch
    %patch -p1 < $pkgfiles/corelib.patch
    rm -r 3rdparty
    ./configure --prefix=%installroot%/%PREFIX% --libdir=%libdir% --datadir=/usr/share
build      : |
    pushd src
    %make
    popd
install    : |
    pushd src
    %make_install
    popd
