name       : deepin-screenshot
version    : 4.0.11
release    : 4
source     :
    - git|https://cr.deepin.io/deepin-screenshot.git : 4.0.11
license    : GPL-3.0
component  : desktop.deepin
summary    : Advanced tool to make and edit screenshots
description: |
    Deepin screenshot is an advanced tool to make screenshots on Linux desktop environment. It has a user-friendly UI which eases cropping and saving of screenshot.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(dtkwm)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-util)
    - pkgconfig(xcb)
    - pkgconfig(xext)
    - pkgconfig(xtst)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
