name       : dtkcore
version    : 2.0.7
release    : 4
source     :
    - https://github.com/linuxdeepin/dtkcore/archive/2.0.7.tar.gz : ff9ee1ab25b5487304ee22e896ecce426f20ded5e9196171de68b06e8114c85a
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepint Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
description: |
    Deepint Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
builddeps  :
    - qt5-base-devel
    - pkgconfig(gsettings-qt)
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
