name       : dtkcore
version    : 2.0.5
release    : 1
source     :
    - https://github.com/linuxdeepin/dtkcore/archive/2.0.5.tar.gz : f1a5732b1b0eebd8c33aecedafa84e2daa2cfead9fec31be5f5c85891a9ca52e
license    : GPL-3.0
component  : programming.devel
summary    : Deepint Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
description: |
    Deepint Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
builddeps  :
    - qt5-base-devel
    - pkgconfig(gsettings-qt)
setup      : |
    mkdir Build
    pushd Build
    %qmake ..
    popd
build      : |
    pushd Build
    %make
    popd
install    : |
    pushd Build
    %make_install INSTALL_ROOT=$installdir
    popd
