name       : dtkcore
version    : 2.0.6
release    : 3
source     :
    - https://github.com/linuxdeepin/dtkcore/archive/2.0.6.tar.gz : ed712c6f0830a1e9835e8c3cd0ca1f556ae28510de3d90e2cebc2abe87f60e09
license    : GPL-3.0
component  : programming.devel
summary    : Deepint Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
description: |
    Deepint Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
builddeps  :
    - qt5-base-devel
    - pkgconfig(gsettings-qt)
setup      : |
    mkdir Build
    pushd Build
    %qmake ..
    popd
build      : |
    pushd Build
    %make
    popd
install    : |
    pushd Build
    %make_install INSTALL_ROOT=$installdir
    popd
