name       : dtkcore
version    : 2.0.8
release    : 10
source     :
    - git|https://cr.deepin.io/dtkcore.git : 2.0.8
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer
    work on Deepin.
description: |
    Deepin Tool Kit (Dtk) is the base devlopment tool of all C++/Qt Developer work on Deepin.
builddeps  :
    - pkgconfig(gsettings-qt)
    - qt5-base-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
