name       : deepin-default-settings
version    : 2019.1.14
release    : 14
source     :
    - git|https://github.com/linuxdeepin/default-settings.git : 2019.1.14
license    : LGPL-3.0-or-later
component  : desktop.deepin.core
summary    : Deepin default settings
description: |
    Deepin default settings
rundeps    :
    - deepin-introduction
setup      : |
    %apply_patches
install    : |
    %make_install
