name       : deepin-default-settings
version    : 2018.5.31
release    : 2
source     :
    - git|https://cr.deepin.io/default-settings.git : 2018.5.31
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin default settings
description: |
    Deepin default settings
rundeps    :
    - deepin-introduction
setup      : |
    %apply_patches
install    : |
    %make_install
