name       : deepin-default-settings
version    : 2018.8.8
release    : 12
source     :
    - git|https://github.com/linuxdeepin/default-settings.git : 2018.8.8
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin default settings
description: |
    Deepin default settings
rundeps    :
    - deepin-introduction
setup      : |
    %apply_patches
install    : |
    %make_install
