name       : libbson
version    : 1.9.3
release    : 5
source     :
    - https://github.com/mongodb/libbson/archive/1.9.3.tar.gz : 13b47f23f9ebfcbe91da81f85c9e1111aea2419df0116ce7cd1cbfb2af212c38
license    : Apache-2.0
component  : programming.library
summary    : A BSON utility library.
description: |
    libbson is a library providing useful routines related to building, parsing, and iterating BSON documents.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    libtool --finish $installdir/%libdir%
