name       : libbson
version    : 1.9.0_rc0
release    : 2
source     :
    - https://github.com/mongodb/libbson/archive/1.9.0-rc0.tar.gz : acda3dbbe89a22f9e82c442952e389b42e83617bfb4c72a959f7ad61c3693478
license    : Apache-2.0
component  : programming.library
summary    : A BSON utility library.
description: |
    libbson is a library providing useful routines related to building, parsing, and iterating BSON documents.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    libtool --finish $installdir/%libdir%
