name       : libbson
version    : 1.9.5
release    : 8
source     :
    - https://github.com/mongodb/libbson/archive/1.9.5.tar.gz : af1aa8a00a47cf66717f2467f63cbe72401f53b4acd1af1fc2136ede4482c89a
license    : Apache-2.0
component  : programming.library
summary    : A BSON utility library.
description: |
    libbson is a library providing useful routines related to building, parsing, and iterating BSON documents.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    libtool --finish $installdir/%libdir%
