name       : libbson
version    : 1.9.4
release    : 7
source     :
    - https://github.com/mongodb/libbson/archive/1.9.4.tar.gz : 6b1bbd52dcc688e005c8784cb5637f2f16b34a825f251a6b57597edea3cea2a7
license    : Apache-2.0
component  : programming.library
summary    : A BSON utility library.
description: |
    libbson is a library providing useful routines related to building, parsing, and iterating BSON documents.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    libtool --finish $installdir/%libdir%
