name       : deepin-image-viewer
version    : 1.3.7
release    : 24
source     :
    - git|https://github.com/linuxdeepin/deepin-image-viewer.git : 1.3.7
license    : GPL-3.0-or-later
component  : desktop.deepin
summary    : Deepin Desktop Environment Image Viewer.
description: |
    Deepin Image Viewer is Deepin Desktop Environment Image Viewer.
builddeps  :
    - freeimage-devel
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - pkgconfig(libexif)
    - pkgconfig(libraw)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5integration
    - freeimage-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
