name       : deepin-polkit-agent
version    : 0.2.1
release    : 7
source     :
    - git|https://cr.deepin.io/dde/dde-polkit-agent.git : 0.2.1
license    : GPL-3.0
component  : desktop
summary    : Deepin Polkit Agent
description: |
    Deepin Polkit Agent
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(polkit-qt5-1)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
