name       : deepin-polkit-agent
version    : 0.2.1
release    : 4
source     :
    - https://github.com/linuxdeepin/dde-polkit-agent/archive/0.2.1.tar.gz : b1107923409ec4916a7a6c28a79aec4aa71904aa378277f697ad0436052b3060
license    : GPL-3.0
component  : desktop
summary    : Deepin Polkit Agent
description: |
    Deepin Polkit Agent
builddeps  :
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(polkit-qt5-1)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
