name       : deepin-polkit-agent
version    : 0.2.0
release    : 3
source     :
    - https://github.com/linuxdeepin/dde-polkit-agent/archive/0.2.0.tar.gz : ea069778eac421005abc07eea538dcb58c48754c832c81221c0fd95a8d9cbc2a
license    : GPL-3.0
component  : desktop
summary    : Deepin Polkit Agent
description: |
    Deepin Polkit Agent
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(dframeworkdbus)
    - pkgconfig(glu)
    - pkgconfig(polkit-qt5-1)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
