name       : deepin-icon-theme
version    : 15.12.64
release    : 20
source     :
    - git|https://github.com/linuxdeepin/deepin-icon-theme.git : 15.12.64
license    : GPL-3.0
component  : desktop.theme
summary    : Deepin Icons
description: |
    Deepin Icons
rundeps    :
    - papirus-icon-theme
install    : |
    %make_install
