name       : deepin-icon-theme
version    : 15.12.57
release    : 10
source     :
    - git|https://cr.deepin.io/deepin-icon-theme.git : 15.12.57
license    : GPL-3.0
component  : desktop.theme
summary    : Deepin Icons
description: |
    Deepin Icons
rundeps    :
    - papirus-icon-theme
install    : |
    %make_install
