name       : deepin-icon-theme
version    : 15.12.52
release    : 2
source     :
    - https://github.com/linuxdeepin/deepin-icon-theme/archive/15.12.52.tar.gz : 8973efa24ea4c614740e46354b5332f713246dc76c0433100f87e2fe821ba4f5
license    : GPL-3.0
component  : desktop.theme
summary    : Deepin Icons
description: |
    Deepin Icons
rundeps    :
    - papirus-icon-theme
install    : |
    %make_install
