name       : deepin-icon-theme
version    : 15.12.53
release    : 3
source     :
    - https://github.com/linuxdeepin/deepin-icon-theme/archive/15.12.53.tar.gz : ee2b5685d3582fbe0339615e3d48742273d393e5e7feb9d9f462bf04e2b97e01
license    : GPL-3.0
component  : desktop.theme
summary    : Deepin Icons
description: |
    Deepin Icons
rundeps    :
    - papirus-icon-theme
install    : |
    %make_install
