name       : deepin-screen-recorder
version    : 2.7.3
release    : 1
source     :
    - https://github.com/linuxdeepin/deepin-screen-recorder/archive/2.7.3.tar.gz : a37700f4d7b2b2ce83ca853ea253b979503e3dfc4020e677ccaaab12a93dacae
license    : GPL-3.0
component  : desktop.deepin
summary    : Default screen recorder application for Deepin.
description: |
    a screen recorder tool, it supports to save the recorded screens as gif or mp4 format. It can select the recorded window automatically or manually by selecting the area. Users just need to start and stop the recording process, and the file will auto save to the desktop.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(dtkwm)
    - pkgconfig(libprocps)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcb-util)
    - pkgconfig(xtst)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
