name       : deepin-calendar
version    : 1.2.2
release    : 1
source     :
    - https://github.com/linuxdeepin/dde-calendar/archive/1.2.2.tar.gz : 9ef7c26916d173ef19d0e4729ed9c075d322364054498d8013ba3169c3c4d4fb
license    : GPL-3.0
component  : deepin.desktop
summary    : Calendar for Deepin Desktop Environment.
description: |
    Deepin Calender is an easy calendar tool developed by Deepin Technology, main features current date, solar terms, lunar calendar and world holidays.
builddeps  :
    - deepin-gettext-tools
    - pkgconfig(dtkwidget)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5dxcb-plugin
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
