name       : deepin-artwork-themes
version    : 15.12.4
release    : 1
source     :
    - https://github.com/linuxdeepin/deepin-artwork-themes/archive/15.12.4.tar.gz : f193fdd9efa2d03a085976adc570f8b274d95ac38030e7c0d7194b7218d9f153
license    : GPL-3.0
component  : desktop.theme
summary    : Deepin artwork themes.
description: |
    Deepin artwork themes.
rundeps    :
    - deepin-desktop-base
    - deepin-icon-theme
build      : |
    %make
install    : |
    %make_install
