name       : deepin-picker
version    : 1.6.2
release    : 8
source     :
    - git|https://cr.deepin.io/deepin-picker.git : 1.6.2
license    : GPL-3.0
component  : desktop.deepin
summary    : Simplest color picker.
description: |
    Deepin Picker is a fast screen color picking tool developed by Deepin Technology. The RGB, RGBA, HEX, CMYK and HSV code can be obtained according color picked and auto saved to the clipboard.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-util)
    - pkgconfig(xcb)
    - pkgconfig(xtst)
    - qt5-tools-devel
rundeps    :
    - gtk2-engine-murrine
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
