name       : deepin-gettext-tools
version    : 1.0.8
release    : 2
source     :
    - https://github.com/linuxdeepin/deepin-gettext-tools/archive/1.0.8.tar.gz : b8d1a3857032ed9186e0ee54277706f082b03c9fa7c874cf1bc0c046aeb1ddb7
license    : GPL-3.0
component  : programming.tools
summary    : Deepin Gettext Tools
description: |
    Deepin Gettext Tools
rundeps    :
    - perl-config-tiny
    - perl-xml-libxml
install    : |
    %make_install
