name       : deepin-gir-generator
version    : 1.2.0
release    : 20
source     :
    - git|https://github.com/linuxdeepin/go-gir-generator.git : 1.2.0
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Static golang bindings for GObject.
description: |
    Static golang bindings for GObject.
builddeps  :
    - golang
setup      : |
    %patch -p1 < $pkgfiles/SettingsBackendLike.patch
build      : |
    export GOPATH="${workdir}"
    %make
install    : |
    %make_install
