name       : deepin-gir-generator
version    : 1.0.3
release    : 5
source     :
    - git|https://cr.deepin.io/go-gir-generator : 1.0.3
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Static golang bindings for GObject.
description: |
    Static golang bindings for GObject.
builddeps  :
    - golang
build      : |
    export GOPATH="${workdir}"
    %make
install    : |
    %make_install
