name       : deepin-file-manager
version    : 4.4.8.2
release    : 4
source     :
    - https://github.com/linuxdeepin/dde-file-manager/archive/4.4.8.2.tar.gz : 195a7502dea2dc9863c5f9e98683649876677b0e3c442eda969d1b81b5ce19b7
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Deepin File Manager is a file management tool developed for Deepin
description: |
    Deepin File Manager is a file management tool independently developed by Deepin Technology, featured with searching, copying, trash, compression/decompression, file property and other file management functions.
builddeps  :
    - deepin-dock-devel
    - deepin-gettext-tools
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gsettings-qt)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libsecret-1)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(poppler-cpp)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(taglib)
    - pkgconfig(uchardet)
    - pkgconfig(xcb-ewmh)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
