name       : deepin-file-manager
version    : 4.4.7
release    : 3
source     :
    - https://github.com/linuxdeepin/dde-file-manager/archive/4.4.7.tar.gz : a9fdbf9fa9a4d2037e05f6e7b357728b420212c4f789f2fb042ed2b7d62e40d8
license    : GPL-3.0
component  : desktop.deepin
summary    : Deepin File Manager is a file management tool developed for Deepin
description: |
    Deepin File Manager is a file management tool independently developed by Deepin Technology, featured with searching, copying, trash, compression/decompression, file property and other file management functions.
builddeps  :
    - deepin-dock-devel
    - deepin-gettext-tools
    - pkgconfig(dframeworkdbus)
    - pkgconfig(dtkwidget)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gsettings-qt)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libsecret-1)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(poppler-cpp)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(taglib)
    - pkgconfig(uchardet)
    - pkgconfig(x11)
    - pkgconfig(xcb-ewmh)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
