name       : deepin-system-monitor
version    : 1.4.3
release    : 5
source     :
    - https://github.com/linuxdeepin/deepin-system-monitor/archive/1.4.3.tar.gz : 35c68d6d99cb8504c26f0d6eef3a6510d0dcd4cce3a41c5e0f820fa99404ba55
license    : GPL-3.0
component  : desktop.deepin
summary    : A more user-friendly system monitor.
description: |
    Deepin system monitor: a more user-friendly system monitor.
builddeps  :
    - libpcap-devel
    - pkgconfig(dtkwidget)
    - pkgconfig(dtkwm)
    - pkgconfig(libprocps)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - pkgconfig(xcb-util)
    - pkgconfig(xext)
    - pkgconfig(xtst)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5dxcb-plugin
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
