name       : deepin-system-monitor
version    : 1.4.3
release    : 7
source     :
    - git|https://cr.deepin.io/deepin-system-monitor.git : 1.4.3
license    : GPL-3.0
component  : desktop.deepin
summary    : A more user-friendly system monitor.
description: |
    Deepin system monitor: a more user-friendly system monitor.
builddeps  :
    - libpcap-devel
    - pkgconfig(dtkwidget)
    - pkgconfig(dtkwm)
    - pkgconfig(libprocps)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-util)
    - pkgconfig(xcb)
    - pkgconfig(xext)
    - pkgconfig(xtst)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5integration
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
