name       : deepin-wm
version    : 1.9.24
release    : 4
source     :
    - https://github.com/linuxdeepin/deepin-wm/archive/1.9.24.tar.gz : 025b6a3828df4fda55827ff5a4426de13560a3d02101c3cf0d7ec46add419309
license    : GPL-3.0
component  : desktop
summary    : Deepin Window Manager
description: |
    Default window manager for Deepin, started as a fork of Elementary Gala, based on libmutter. Mostly rewritten to work with Deepin Desktop Environment, such as redesign the UI for window switching, enhance user experience for the workspace preview mode, support multiple backgrounds, and many of other changes.
builddeps  :
    - deepin-clutter-devel
    - deepin-clutter-gtk-devel
    - gnome-common
    - pkgconfig(gdk-x11-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libcanberra)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libdeepin-mutter)
    - pkgconfig(libwnck-3.0)
    - vala
rundeps    :
    - deepin-desktop-schemas
setup      : |
    %autogen --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
