name       : deepin-network-utils
version    : 0.1.0
release    : 12
source     :
    - git|https://github.com/linuxdeepin/dde-network-utils.git : 0.1.0
license    : GPL-3.0-or-later
component  : desktop.deepin.core
summary    : Deepin network utilities
description: |
    Deepin network utilities
builddeps  :
    - pkgconfig(dframeworkdbus)
    - qt5-tools-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
