name       : deepin-shortcut-viewer
version    : 1.3.4
release    : 4
source     :
    - https://github.com/linuxdeepin/deepin-shortcut-viewer/archive/1.3.4.tar.gz : e870785e0f1c038adf606d0382349870b410b76acd7726d851d3b6809a10823b
license    : GPL-3.0
component  : desktop
summary    : Deepin Shortcut Viewer
description: |
    Helps Deepin applications pop up their shortcut information on screen in a unified appearance.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
