name       : deepin-shortcut-viewer
version    : 1.3.4
release    : 6
source     :
    - git|https://cr.deepin.io/deepin-shortcut-viewer.git : 1.3.4
license    : GPL-3.0
component  : desktop
summary    : Deepin Shortcut Viewer
description: |
    Helps Deepin applications pop up their shortcut information on screen in a unified appearance.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
