name       : deepin-shortcut-viewer
version    : 1.3.3
release    : 2
source     :
    - https://github.com/linuxdeepin/deepin-shortcut-viewer/archive/1.3.3.tar.gz : de99f56240f722ac83bc0bb0204aab99ceb98ae547b75faeb9700c76cdd3fa5d
license    : GPL-3.0
component  : desktop
summary    : Deepin Shortcut Viewer
description: |
    Deepin Shortcut Viewer
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(gl)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
