name       : qt5-xcb-private-headers
version    : 5.9.2
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/5.9/5.9.2/submodules/qtbase-opensource-src-5.9.2.tar.xz : 7fe2bb468955f633c71b3ddd3c269e68a2c4137a4e5b8dd12dcdb34cbc6d609b
license    :
    - FDL-1.3
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Private headers for Qt5 Xcb
description: |
    Private headers for Qt5 Xcb
rundeps    :
    - qt5-base
install    : |
  install -d -m0755 "${installdir}/usr/include/qtxcb-private"
  cp -r src/plugins/platforms/xcb/*.h "${installdir}/usr/include/qtxcb-private/"
