name       : qt5-xcb-private-headers
version    : 5.11.1
release    : 11
source     :
    - https://download.qt.io/official_releases/qt/5.11/5.11.1/submodules/qtbase-everywhere-src-5.11.1.tar.xz : a0d047b2da5782c8332c59ae203984b64e4d5dc5f4ba9c0884fdbe753d0afb46
license    :
    - FDL-1.3
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Private headers for Qt5 Xcb
description: |
    Private headers for Qt5 Xcb
rundeps    :
    - qt5-base
install    : |
    install -d -m0755 "${installdir}/usr/include/qtxcb-private"
    cp -r src/plugins/platforms/xcb/*.h "${installdir}/usr/include/qtxcb-private/"
