name       : libqcef
version    : 1.1.3
release    : 1
source     :
    - https://github.com/linuxdeepin/qcef/archive/1.1.3.tar.gz : 81a2b800a3729a0177f7e3c92ea215821a75806dde090a300016bb30d1120586
license    : LGPL-3.0
component  : programming.library
summary    : Qt5 binding of CEF
description: |
    Qt5 binding of CEF
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gl)
    - pkgconfig(gtk+-x11-2.0)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
