name       : deepin-dbus-factory
version    : 3.1.12
release    : 2
source     :
    - https://github.com/linuxdeepin/dbus-factory/archive/3.1.12.tar.gz : 733c0b6a0a932eb03809c1409d51a6cb5729cde674142566d64187c29682d6c3
license    : GPL-3.0
component  : programming.devel
summary    : GO DBus factory for Deepin
description: |
    GO DBus factory for Deepin
builddeps  :
    - jq
    - deepin-dbus-generator
build      : |
    %make
install    : |
    %make_install GOPATH=/usr/share/gocode
