name       : deepin-dbus-factory
version    : 3.1.13
release    : 3
source     :
    - https://github.com/linuxdeepin/dbus-factory/archive/3.1.13.tar.gz : 1a74116d017774ffe779c9923ddea4122e7f678439dc571ad7668baf35defb92
license    : GPL-3.0
component  : desktop.deepin.core
summary    : GO DBus factory for Deepin
description: |
    GO DBus factory for Deepin
builddeps  :
    - jq
    - deepin-dbus-generator
build      : |
    %make
install    : |
    %make_install GOPATH=/usr/share/gocode
