name       : startdde
version    : 3.1.20
release    : 2
source     :
    - https://github.com/linuxdeepin/startdde/archive/3.1.20.tar.gz : a7c35962b04d18f3e2d32b88590caa65dfdec87086e1b3bc2fc34e0387649a98
networking : yes
license    : GPL-3.0
component  : desktop
summary    : Starter of deepin desktop environment
description: |
    Launches Deepin Desktop Envrionment components and invoking user's custom applications which compliant with xdg autostart specification.
builddeps  :
    - deepin-api
    - deepin-dbus-factory
    - deepin-gir-generator
    - deepin-go-lib
    - git
    - golang
    - pkgconfig(gdk-3.0)
    - pkgconfig(libcanberra)
rundeps    :
    - deepin-daemon
    - deepin-wm-switcher
setup      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    go get github.com/BurntSushi/xgb
    go get github.com/BurntSushi/xgbutil
    go get github.com/howeyc/fsnotify
build      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    %make
install    : |
    %make_install
    mv ${installdir}/lib/systemd ${installdir}/usr/lib/systemd
    rmdir ${installdir}/lib
    ln -sf ../dde-readahead.service ${installdir}/usr/lib/systemd/system/multi-user.target.wants/dde-readahead.service
