name       : startdde
version    : 3.1.26
release    : 6
source     :
    - https://github.com/linuxdeepin/startdde/archive/3.1.26.tar.gz : 5a8d65b09b6e94956c36c0869ffd2550daa1ced1833fd7b0aff18e656b2aa8ad
networking : yes
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Starter of deepin desktop environment
description: |
    Launches Deepin Desktop Envrionment components and invoking user's custom applications which compliant with xdg autostart specification.
builddeps  :
    - deepin-api
    - deepin-dbus-factory
    - deepin-gir-generator
    - deepin-go-lib
    - git
    - golang
    - pkgconfig(alsa)
    - pkgconfig(gdk-3.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libpulse-simple)
    - pkgconfig(x11)
    - pkgconfig(xi)
rundeps    :
    - deepin-control-center
    - deepin-daemon
    - deepin-desktop
    - deepin-dock
    - deepin-gtk-theme
    - deepin-icon-theme
    - deepin-launcher
    - deepin-polkit-agent
    - deepin-session-ui
    - deepin-sound-theme
    - deepin-wm-switcher
setup      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    go get github.com/cryptix/wav
    go get github.com/BurntSushi/xgb
    go get github.com/BurntSushi/xgbutil
build      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    %make
install    : |
    %make_install
