name       : deepin-desktop-schemas
version    : 3.2.9
release    : 5
source     :
    - https://github.com/linuxdeepin/deepin-desktop-schemas/archive/3.2.9.tar.gz : 2081c75156450cb376623ccf35020bad8f6543186cf9f9aa1210491580ad2a1d
license    : GPL-3.0
component  : desktop
summary    : GSettings Deepin desktop-wide schemas
description: |
    GSettings Deepin desktop-wide schemas
build      : |
    %make
install    : |
    %make_install
