name       : deepin-desktop-schemas
version    : 3.2.6
release    : 3
source     :
    - https://github.com/linuxdeepin/deepin-desktop-schemas/archive/3.2.6.tar.gz : 57ef7f17fd48f9a1dd51ef28ce77a2822735d46d314548be6ec0cb43aa611702
license    : GPL-3.0
component  : desktop
summary    : GSettings Deepin desktop-wide schemas
description: |
    GSettings Deepin desktop-wide schemas
build      : |
    %make
install    : |
    %make_install
