name       : deepin-desktop-schemas
version    : 3.2.12
release    : 13
source     :
    - git|https://cr.deepin.io/deepin-desktop-schemas.git : 3.2.12
license    : GPL-3.0
component  : desktop
summary    : GSettings Deepin desktop-wide schemas
description: |
    GSettings Deepin desktop-wide schemas
build      : |
    %make
install    : |
    %make_install
