name       : deepin-qt5dxcb-plugin
version    : 1.1.8.3
release    : 3
source     :
    - https://github.com/linuxdeepin/qt5dxcb-plugin/archive/1.1.8.3.tar.gz : 31ad4796f11341c1e0ae9020cc0ce1ce5735996eae5bf481eb4193f9001cf781
license    : GPL-3.0
component  : desktop.qt
summary    : Qt platform plugins for DDE
description: |
    Qt platform plugins for DDE
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(egl)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(mtdev)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(x11-xcb)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon-x11)
    - qt5-tools-devel
    - qt5-xcb-private-headers-devel
setup      : |
    rm -r platformplugin/libqt5xcbqpa-dev
    %patch -p1 < $pkgfiles/qtfix.patch
    mkdir build
    pushd build
    %qmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
