name       : deepin-wallpapers
version    : 1.7
release    : 3
source     :
    - https://github.com/linuxdeepin/deepin-wallpapers/archive/1.7.tar.gz : 499dd978b80fb271045fce525adafdcffda0c8cc1f735d1f458191b52b08cb41
license    : GPL-3.0
component  : desktop
summary    : Deepin Wallpapers
description: |
    Deepin Wallpapers
builddeps  :
    - deepin-api
build      : |
    %make
install    : |
    install -dm0755 "${installdir}/usr/share/wallpapers"
    cp -r deepin "${installdir}/usr/share/wallpapers/"

    install -dm0755 "${installdir}/var/cache"
    cp -r image-blur "${installdir}/var/cache/"
