name       : deepin-notifications
version    : 3.2.2.1
release    : 8
source     :
    - git|https://cr.deepin.io/deepin-notifications.git : 3.2.2.1
license    : GPL-3.0
component  : desktop
summary    : An implementation of Gnome Desktop Notifications Specification
description: |
    An implementation of Gnome Desktop Notifications Specification
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
