name       : deepin-notifications
version    : 3.3.1
release    : 15
source     :
    - git|https://cr.deepin.io/deepin-notifications.git : 3.3.1
license    : GPL-3.0
component  : desktop
summary    : An implementation of Gnome Desktop Notifications Specification
description: |
    An implementation of Gnome Desktop Notifications Specification
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(gsettings-qt)
    - pkgconfig(Qt5Svg)
    - qt5-tools-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
