name       : deepin-notifications
version    : 3.2.1
release    : 5
source     :
    - https://github.com/linuxdeepin/deepin-notifications/archive/3.2.1.tar.gz : 2c4906f5d18b930133aa7e3b8f96cc6b58ab8d6815472f4f282a4813986b40c1
license    : GPL-3.0
component  : desktop
summary    : An implementation of Gnome Desktop Notifications Specification
description: |
    An implementation of Gnome Desktop Notifications Specification
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(Qt5Svg)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
