name       : deepin-notifications
version    : 3.2.2
release    : 6
source     :
    - https://github.com/linuxdeepin/deepin-notifications/archive/3.2.2.tar.gz : ea552ae359c7abe776ab622c52b4a82b416fe0c405c137d3b13ddbcee5be4a34
license    : GPL-3.0
component  : desktop
summary    : An implementation of Gnome Desktop Notifications Specification
description: |
    An implementation of Gnome Desktop Notifications Specification
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(glu)
    - pkgconfig(Qt5Svg)
    - qt5-tools-devel
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
