name       : freeimage
version    : 3.17.0
release    : 1
source     :
    - https://sourceforge.net/projects/freeimage/files/Source%20Distribution/3.17.0/FreeImage3170.zip/download : fbfc65e39b3d4e2cb108c4ffa8c41fd02c07d4d436c594fff8dab1a6d5297f89
license    :
    - GPL-2.0
    - GPL-3.0
    - FIPL
component  : multimedia.library
summary    : Library to support popular graphics image formats.
clang      : yes
description: |
    FreeImage is an Open Source library project for developers who would like to support popular graphics image formats like PNG, BMP, JPEG, TIFF and others as needed by today's multimedia applications. FreeImage is easy to use, fast, multithreading safe, compatible with all 32-bit or 64-bit versions of Windows, and cross-platform (works both with Linux and Mac OS X).
#builddeps  :
build      : |
    %make
install    : |
    %make_install
