name       : deepin-account-faces
version    : 1.0.10
release    : 6
source     :
    - git|https://cr.deepin.io/dde/dde-account-faces.git : 1.0.10
license    : GPL-3.0
component  : desktop.deepin.core
summary    : Account faces for Linux Deepin
description: |
    Account faces for Linux Deepin
build      : |
    %make
install    : |
    %make_install
