name       : proxychains-ng
version    : 4.12
release    : 3
source     :
    - https://github.com/rofl0r/proxychains-ng/archive/v4.12.tar.gz : b7bc3062e463800b7718789708defa379da41934231d6cb171defc0eae188b08
license    : GPL-2.0
component  : network.util
summary    : A preloader which hooks calls to sockets in dynamically linked programs
    and redirects it through one or more socks/http proxies
description: |
    ProxyChains is a UNIX program, that hooks network-related libc functions in DYNAMICALLY LINKED programs via a preloaded DLL (dlsym(), LD_PRELOAD) and redirects the connections through SOCKS4a/5 or HTTP proxies. It supports TCP only (no UDP/ICMP etc).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
