name       : deepin-daemon
version    : 3.2.6
release    : 1
source     :
    - https://github.com/linuxdeepin/dde-daemon/archive/3.2.6.tar.gz : e86267b5f7e9f161111a67f7e7e3a77fc1d5121b7e097b7c7f075f35d6272de7
networking : yes
license    : GPL-3.0
component  : desktop
summary    : Daemon handling the DDE session settings
description: |
    Daemon handling the DDE session settings
builddeps  :
    - deepin-api
    - deepin-dbus-factory
    - deepin-gettext-tools
    - deepin-gir-generator
    - deepin-go-lib
    - git
    - golang
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libinput)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnl-genl-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libudev)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
rundeps    :
    - accountsservice
    - bamf
    - bluez
    - deepin-desktop-base
    - deepin-desktop-schemas
    - deepin-notifications
    - deepin-polkit-agent
    - gnome-keyring
    - gvfs
    - iw
    - libxkbfile
    - lsb-release
    - mobile-broadband-provider-info
    - network-manager
    - noto-sans-ttf
    - poppler
    - rfkill
    - udisks
    - upower
setup      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    %patch -p1 < $pkgfiles/nm-1.10.patch
    %patch -p1 < $pkgfiles/desktop.patch
    %patch -p1 < $pkgfiles/dde-daemon_3.2.3.patch
    %patch -p1 < $pkgfiles/libdir.patch
    go get github.com/axgle/mahonia
    go get github.com/BurntSushi/freetype-go/freetype
    go get github.com/BurntSushi/freetype-go/freetype/truetype
    go get github.com/BurntSushi/graphics-go/graphics
    go get github.com/BurntSushi/xgb
    go get github.com/BurntSushi/xgbutil
    go get github.com/disintegration/imaging
    go get github.com/howeyc/fsnotify
    go get github.com/linuxdeepin/go-x11-client
    go get github.com/mattn/go-sqlite3
    go get github.com/msteinert/pam
    go get github.com/nfnt/resize
    go get golang.org/x/sys/unix
    go get golang.org/x/text/encoding/charmap
    go get gopkg.in/alecthomas/kingpin.v2
    go get gopkg.in/yaml.v2
build      : |
    export GOPATH="${workdir}/:/usr/share/gocode"
    %make
install    : |
    %make_install 
