name       : deepin-movie
version    : 3.2.3
release    : 1
source     :
    - https://github.com/linuxdeepin/deepin-movie-reborn/archive/3.2.3.tar.gz : beede0f263303052f326d32e893187b23cf8ab525ef6d0fb1f6e92b088cc19eb
license    : GPL-3.0
component  : desktop.deepin
summary    : Deepin Movie Player.
description: |
    Deepin Movie provides an intuitive easy to use operation interface and rich complete shortcuts. You can complete all play operations by keyboard, which will make you thoroughly get rid of the constraint of mouse click. Video files in various formats can be played through Deepin Movie, and you can use the streaming function to easily enjoy online video resources.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(dvdnav)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libavformat)
    - pkgconfig(libavresample)
    - pkgconfig(libavutil)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libpulse)
    - pkgconfig(libpulse-simple)
    - pkgconfig(mpv)
    - pkgconfig(Qt5Concurrent)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Network)
    - pkgconfig(Qt5Sql)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-aux)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-proto)
    - pkgconfig(xtst)
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
