name       : deepin-cogl
version    : 1.22.5
release    : 1
source     :
    - https://github.com/linuxdeepin/deepin-cogl/archive/1.22.5.tar.gz : fb86a54084e45cd80b9785ab6a1457ff50005467e215221d037bd1bf81485d98
license    : GPL-2.0
component  : desktop
conflicts  :
    - cogl
summary    : An object oriented GL/GLES Abstraction/Utility Layer for Deepin
description: |
    An object oriented GL/GLES Abstraction/Utility Layer for Deepin
builddeps  :
    - gtk-doc
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gl)
    - pkgconfig(pangocairo)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
setup      : |
    %autogen --disable-static \
             --enable-glib \
             --enable-cogl-pango \
             --disable-cogl-gst \
             --enable-gdk-pixbuf \
             --enable-examples-install \
             --enable-gles2 \
             --enable-gl \
             --enable-cogl-gles2 \
             --enable-glx \
             --enable-wayland-egl-platform \
             --enable-kms-egl-platform \
             --enable-wayland-egl-server \
             --enable-xlib-egl-platform
build      : |
    %make
install    : |
    %make_install
    libtool --finish $installdir/%libdir%
