name       : deepin-voice-recorder
version    : 1.3.6.1
release    : 2
source     :
    - https://github.com/linuxdeepin/deepin-voice-recorder/archive/1.3.6.1.tar.gz : 5e93de413f15cdbd6ba8152384cd7215da53bb698e7e7b241197a13a8b62ff82
license    : GPL-3.0
component  : desktop.deepin
summary    : Default voice recorder application for Deepin.
description: |
    Deepin Voice Recorder is a beautiful and easy to use voice recording application with simple design. No matter recording your singing, phone call or meeting conversation, you can finish all these tasks by Deepin Voice Recorder. It also supports visual recording, recording playback, recording list management and other functions.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(libavformat)
    - pkgconfig(Qt5Multimedia)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5dxcb-plugin
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
