name       : deepin-voice-recorder
version    : 1.3.6.1
release    : 5
source     :
    - git|https://cr.deepin.io/deepin-voice-recorder.git : 1.3.6.1
license    : GPL-3.0
component  : desktop.deepin
summary    : Default voice recorder application for Deepin.
description: |
    Deepin Voice Recorder is a beautiful and easy to use voice recording application with simple design. No matter recording your singing, phone call or meeting conversation, you can finish all these tasks by Deepin Voice Recorder. It also supports visual recording, recording playback, recording list management and other functions.
builddeps  :
    - pkgconfig(dtkwidget)
    - pkgconfig(libavformat)
    - pkgconfig(Qt5Multimedia)
    - qt5-tools-devel
rundeps    :
    - deepin-qt5integration
setup      : |
    mkdir build
    pushd build
    %qmake .. PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install INSTALL_ROOT=$installdir
    popd
