name       : deepin-webengine
version    : 5.9.4.1
release    : 1
source     :
    - git|https://github.com/linuxdeepin/deepin-webengine.git : cc9c38dccc678c50588a74194b09917bc5edfb4d
license    : GPL-2.0 # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-io)
    - pkgconfig(jsoncpp)
    - pkgconfig(lcms2)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(libdrm)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libsrtp2)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(minizip)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(vpx)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - gperf
    - ninja
    - re2-devel
    - snappy-devel
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    unset LDFLAGS
    export CXXFLAGS="${CXXFLAGS/-fexceptions/} -fno-exceptions"
    qmake
build      : |
    unset LDFLAGS
    export CXXFLAGS="${CXXFLAGS/-fexceptions/} -fno-exceptions"
    %make
install    : |
    unset LDFLAGS
    %make_install INSTALL_ROOT=$installdir
